### ISSUE TITLE
Optional prop types should allow null

### ISSUE THREAD

**Issue by rjbailey** [CalebMorris/react-moment-proptypes#10] opened 2016-01-05 23:18 UTC
The default behavior of React's optional prop types is to allow `null` or `undefined`. Right now moment-proptypes only allows `undefined` when a prop is not required. It would be great if moment-proptypes' behavior was consistent with React's!

**Comment by CalebMorris** [comment] 2016-01-15 03:21
@rjbailey Merged PR to fix this (and some updates to the React renderer for tests) and updated npm package to v1.1.0.
Let me know if you run into any problems as I did very little tests (and ran into some oddities that should have been caused by an ancient version of react I had).
Thanks for the assistance in keeping this package to spec.

**Closed as completed by CalebMorris** 2016-01-15 03:21 UTC
